"""empty message

Revision ID: bc0600c67aa4
Revises: eeb3d944d804
Create Date: 2020-12-05 20:54:39.843251

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc0600c67aa4'
down_revision = 'eeb3d944d804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dado_epidemiologico', 'doenca_associada_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dado_epidemiologico', 'doenca_associada_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
