"""empty message

Revision ID: bf58d4392aa3
Revises: 
Create Date: 2020-11-10 07:40:08.731926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf58d4392aa3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doenca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(80), nullable=True),
    sa.Column('sintomas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('dado_epidemiologico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_coleta', sa.DateTime(), nullable=False),
    sa.Column('doenca_associada_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doenca_associada_id'], ['doenca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dado_epidemiologico')
    op.drop_table('doenca')
    # ### end Alembic commands ###
